### ISSUE TITLE
I2S bring up on buildroot

### ISSUE THREAD

**Issue by sachininja** [sachininja/final-project-SachinMathad#12]
DoD:
1. Created a new package on buildroot to load asound config file and wave files.
2. Validated alsa packages working on buildroot
3. Compared required audio modules on raspbian OS and buildroot image to ensure proper working.
5. Verified audio playback on speaker with the buildroot image.
 
Blockers: None

**Comment by dash6424** [comment]
Resolution:
1. Added new package containing required i2s dependent scripts and one wave file for test purpose.
 https://github.com/cu-ecen-aeld/final-project-sachininja/tree/i2s-buildroot

2. 

![Image](https://user-images.githubusercontent.com/112534481/233914819-2c031c2b-5d81-43a8-8ffe-6756784a283b.jpeg)

3. 

![Image](https://user-images.githubusercontent.com/112534481/233915014-cc0b97d6-89ac-489f-a56d-d5f3a4a62ad1.jpeg)

4. Picture in point 2 shows that aplay command where audio playback is running
