### ISSUE TITLE
I2S driver and design plan

### ISSUE THREAD

**Issue by sachininja** [sachininja/final-project-SachinMathad#3]
DoD: 

- Read Rpi Datasheet and DAC module MAX 98357A datasheet for I2S driver.
- Create Integration design plan for RPi.  
- Rig up speaker and CODEC hardware. 

Blockers: None

**Comment by dash6424** [comment]
DoD:

Read Rpi Datasheet and DAC module MAX 98357A datasheet for I2S driver:
 - Understood the working of MAX 98357A w.r.t i2s interface. DAC module converts the data to analog signal and routes it to speaker.
 - https://github.com/cu-ecen-aeld/final-project-dash6424/blob/main/max98357a_hw_codec.pdf
 - Read the RPI data sheet to understand the pin configuration for i2s working.
 - Set the RPI with master clock and set the configuration for i2s working.

Create Integration design plan for RPi.
- Set the asound.conf & config.txt files to instantiate the i2s driver during boot up.
- https://github.com/cu-ecen-aeld/final-project-dash6424/blob/main/asound.conf
- https://github.com/cu-ecen-aeld/final-project-dash6424/blob/main/config.txt

Rig up speaker and CODEC hardware.
- Established hardware connections from RPI -> MAX98357A -> Speaker.
- Verified simple audio playback over the speaker through the i2s interface.

No blockers. All DoD's were completed.
