### ISSUE TITLE
Bluetooth stack

### ISSUE THREAD

**Issue by sachininja** [sachininja/final-project-SachinMathad#4]
DoD: 

- Select the version of Bluez stack to be used. 
- Setup bluez utilities and advertise using rpi controller. 

Blocker: None

**Comment by suja8742** [comment]
DoD:

- Select the version of Bluez stack to be used:
**SJ**: 
- The Bluez Version 5.55 has been selected. The following steps have been performed:
- The bluez5_utils source code has been pushed to the application code repo. 
- The source code has been installed from source and the bluetooth controller was registered. 

Setup bluez utilities and advertise using rpi controller:
**SJ**: 
- Bluez utils 5.55 was setup.
- The systemctl APIs were used to register the controller agent. 
- bluetoothctl was used to power on and advertise and discover using the agent. 
- Connection successful with multiple devices including phones, laptops, headphones etc. 
- I used ObexFTP bluetooth to transfer files over Bluetooth. This was unsuccessful.

**Comment by suja8742** [comment]
Repository link: https://github.com/cu-ecen-aeld/final-project-suja8742
