### ISSUE TITLE
Parsing BLE control data for audio playback.

### ISSUE THREAD

**Issue by sachininja** [sachininja/final-project-SachinMathad#6]
DoD:
1. Create a dummy file for command parsing to mimic received control commands over BLE.
3. Write a script to run commands to play audio over speaker based on user input.
4. Write application to parse dummy file and run the script based on the control commands.

Blockers: This is just dummy file parsing. Actual file is to be received over BLE.
NOTE: The actual audio parsing will be done as part of System Integration and testing

**Comment by dash6424** [comment]
1. Create a dummy file for command parsing to mimic received control commands over BLE.
https://github.com/cu-ecen-aeld/final-project-dash6424/blob/d492996ab8ffec48217ba7d166a17c019770ead2/audio_test.txt

2. Write a script to run commands to play audio over speaker based on user input.
https://github.com/cu-ecen-aeld/final-project-dash6424/blob/main/i2s_sequencer.py

3. Write application to parse dummy file and run the script based on the control commands.
https://github.com/cu-ecen-aeld/final-project-dash6424/blob/main/i2s_sequencer.py

The i2s_sequencer script will continuously poll the audio_test.txt file to see if any new audio control command is received and execute aplay command to play / next / previous / stop the audio playaback. 

audio_test.txt is a dummy file I created. This file will be updated by bluetooth commands that will be received from client to server.

i2s_sequencer is also added with file mutex lock to ensure mutual exclusion when BT server and audio i2s script read/write data to it

Blockers were successfully identified and cleared as the audio_test.txt clears the requirement.
