### ISSUE TITLE
BLE GATT Server - Buildroot

### ISSUE THREAD

**Issue by sachininja** [sachininja/final-project-SachinMathad#7]
DoD:
1. Integrate BLE GATT server image to the buildroot image.
2. Send files to the server RPI.
3. Send and receive data packets.

Blockers: None

**Comment by suja8742** [comment]
Refer to on https://github.com/cu-ecen-aeld/final-project-sachininja for push of the completed buildroot configuration.
Commit hash: e6be9b94e8ac93b0466a3b74b541bde28bc02b31

Used bluetoothctl Bluez 5.63 utility to send and receive data. Next sprint, I will be scripting this to configure the device as a server and integrating into Buildroot image. 

1. Successfully integrated required Bluetooth server packages on buildroot, created a build and ran on RPi. 
2. Successfully connected the Bluetooth agent to Bluez stack, refer to below image. 


![Image](https://user-images.githubusercontent.com/89813802/233928182-fdaddad1-33af-47df-8960-e268e01e62ec.png)

3. Successfully created two custom services and characteristics. One to read and one to write. 

Write: 


![Image](https://user-images.githubusercontent.com/89813802/233929496-064137da-202a-4930-8741-787d73218225.png)

Write - Wrote two values from phone as a client device - 07 and 05.

Read: 



![Image](https://user-images.githubusercontent.com/89813802/233930090-0d10f631-16bf-462e-a6b0-6a977dd52fa4.png)

Read a default value of 0 assigned to the custom characteristic.

All aspects of this sprint are completed.
