### ISSUE TITLE
Automate Server operations

### ISSUE THREAD

**Issue by sachininja** [sachininja/final-project-SachinMathad#9]
DoD:
1. Write a Script to automate server operation for 

- Turning on Bluetooth.
- Creating GATT services
- Advertising.  

2. Integrate and test the script on buildroot rpi build

Blocker: None

**Comment by suja8742** [comment]
78b12b43138a9a4012d168822c337a9919c40faf -  https://github.com/cu-ecen-aeld/final-project-suja8742
514d2428636d2d1a6f27ac66631bdafacfead906 - https://github.com/cu-ecen-aeld/final-project-sachininja
Refer to above commit hashes for code and integrated buildroot image. The second commit hash is present in the integrated_build branch. 

Script automates the functionality of the bluetooth server to expose a custom service and characteristic to the client. It accepts a connection from the client after the configuration and receives data. When data is received, the packet is parsed for a character of concern, and that character is written to a file. This file is read by the I2S module to play the appropriate song from the speaker. In addition, a script has been added to the buildroot rootfs overlay to initalize the bcm43xx bluetooth chip of the Raspberry pi. Credit for this script - VenkatTata. 

This has been integrated and tested on buildroot. 

The image below depicts the script running and accepting data from the bluetooth client. Both the data received and the data stored to the file is displayed. 


![Image](https://user-images.githubusercontent.com/89813802/235418583-52ae0659-b8d1-4c1e-b357-76ab74d14c20.png)


This meets the criteria for the DoD.
